{-# LANGUAGE OverloadedStrings #-}
module Main where

import Control.Monad (when)
import qualified Data.Text as T
import Data.Time.Format ()
import GHC.IO.Encoding (setLocaleEncoding, setFileSystemEncoding, setForeignEncoding, utf8)
import System.Exit (exitSuccess)
import System.IO (hSetEncoding, stdin, stdout, stderr)

import Sched (sched)
import Writer (writePdf)
import Opts (Options(..), getOpts, options, today, usageInfo)

-- This banner generated by using `figlet -f slant sched | sed "s@\\\@\\\\\\\@g"`.
helpMessage :: String
helpMessage = unlines
  [ "              __             __"
  , "   __________/ /_  ___  ____/ /"
  , "  / ___/ ___/ __ \\/ _ \\/ __  / "
  , " (__  ) /__/ / / /  __/ /_/ /  "
  , "/____/\\___/_/ /_/\\___/\\__,_/   "
  , "                               "
  , "Schedule Generator"
  , "> cabal run sched -- [OPTIONS...]"
  , usageInfo "OPTION" options
  ]


initUtf8 :: IO ()
initUtf8 = do
  -- ロケールに依存せず UTF-8 を使う
  setLocaleEncoding utf8
  setFileSystemEncoding utf8
  setForeignEncoding utf8
  -- 標準入出力も UTF-8 固定
  hSetEncoding stdin  utf8
  hSetEncoding stdout utf8
  hSetEncoding stderr utf8

main :: IO ()
main = do
  -- UTF-8 初期化
  initUtf8

  -- コマンドライン引数解析
  opts <- getOpts

  -- ヘルプ表示 & 終了
  when (optHelp opts) $ do
    putStr helpMessage
    exitSuccess

  -- スケジュール作成に必要なオプション取得
  startDate <- maybe today pure $ optStartDate opts
  let unit   = optUnitMax opts
  let n      = optNumOfDays opts
  let rep    = optRepetitions opts
  -- スケジュール生成
  let m = sched unit rep startDate n

  -- PDF出力に必要なオプション取得
  let noDate = optNoDate opts
  let title  = maybe "薬袋式英単語暗記シート" T.pack $ optTitle opts
  let out    = maybe "minai-style-sched.tex" id $ optOutputFile opts
  -- PDF出力
  writePdf noDate m title out
